### PR TITLE
Add screen recording functionality for GIFs

### PR DESCRIPTION
**Pull request by FKatenbrink**
This PR adds the functionality to save the screen as requested in #33. Currently, only the GIF format is supported. The default hotkey is _i_. It must be pressed to start and to end the capturing.

### CODE REVIEW

**Comment by FKatenbrink** [comment]
Thanks!

You're right, the saving procedure hangs the program as it takes quite a while to generate a 60 FPS GIF. To speed it up, we could try skipping every second frame and dropping the FPS to 30. Obviously, the quality would suffer.

I also tried running the saving procedure in a separate Thread to not block the emulation, however the saving procedure seems to take most of the CPU, so that the game is unplayable then. Any advice?

**Comment by Baekalfen** [comment]
Personally, I can live with the hanging, as I will only use it occasionally.

I think it's best to leave the FPS at 60 as default, as this is what the Game Boy produces. In the future, we might see a settings window for the emulator, where the FPS could be changed, if the user wants to — alongside changing keyboard keys etc.

If you ran it as a thread, the GIL wouldn't be released, so emulator and saving procedure would be limited to one CPU core. To overcome this, you would have to use `multiprocessing.Process`, and transfer the video data to the separate process. Either it has to be transferred when saving, or frame-by-frame while recording. To transfer the memory, you can either use `multiprocessing.Pipe` to do a server-client style transfer or `multiprocessing.Array` to do it more implicitly.

**Comment by Baekalfen** [comment]
I think you might be interested in the commit I just pushed. It should demonstrate all you need to move the saving to a separate process: dfda9b6. The commit was in reference to #34.

**Comment by Baekalfen** [comment]
I updated your code, @FKatenbrink . Maybe you'll find it interesting :) d6e1a2f91897979e79818aa7702c184210d072cc

**Pull request merged**
