### PR TITLE
Serial Support

### PR DESCRIPTION
**Pull request by Artucuno**
- Merged changes from master branch
- Working implementation of Serial

**Tested in:**
- Pokemon Yellow
  - Trading
  - Battle

**Issues:**
- ~~There is a small issue where the emulator will temporarily freeze when waiting for the other Gameboy to respond to data (Should be an easy fix for someone)~~ - Fixed in 7878718
- Synchronization issues in some games, however Pokémon games work completely fine.
  - Tetris
- When compiled into Cython, PyBoy freezes after socket connection is established

### CODE REVIEW

**Comment by Baekalfen** [comment]
Sorry, I rebased your branch so that it was in line with the history of `master` and `serial`. For some reason, GitHub thought it should close the PR on the force-push...

**Comment by Baekalfen** [comment]
You can pull the branch from here and reopen the PR https://github.com/Baekalfen/PyBoy/tree/artucuno/serial

**Comment by Baekalfen** [comment]
[Trying to reopen]

**Comment by Artucuno** [comment]
No worries, I'll reopen the PR soon 👍

**Pull request closed without merging**
